Updated requirements.txt and README.md instructions
trelby/trelby pull request #25
Opened 2024-07-10 19:58 UTC by Devariiii

While trying to install the .deb the program would just open and close instantly. After some trail and error I figured out that it was a dependency issue. 

I have updated the requirements.txt so it will download the correct packages (for Debian 12 at least) and updated the README.md instructions on how to install through said file. I have also added a note in case of .deb failure to try to download the dependencies manually.

2024-07-16 20:09 UTC, limburgher commented
The requirements.txt file isn't a script, it's for use by pip to install modules locally.  Have you tried the deb builds on OBS?

https://build.opensuse.org/package/show/home:gwync/trelby

2024-07-16 20:56 UTC, Devariiii commented
For the requirements.txt I didn't fully understand what was being done so I reverted my changes.

For the Debian package located at the OpenSuse repositories, it doesn't open unless also using `sudo apt install python3-setuptools wxpython-tools python3-lxml python3-reportlab`. Without that the program will instantly close as soon as it's opened. I've just added the step of installing for Debian packages before installation to the README.md file.

2024-07-16 21:39 UTC, limburgher commented
Perfect, thank you!

2024-07-16 21:40 UTC, merged

2024-12-27 23:00 UTC, flossybloom67 requested changes
- **```
> `~~![Screenshot_20241227-113735.png](https://github.com/user-attachments/assets/c39948f4-63c0-46fd-becc-5fe4341e27bd)

~~`
```**

2024-12-27 23:12 UTC, flossybloom67 approved these changes

2024-12-27 23:13 UTC, flossybloom67 commented
3f0288fcad8777955fb41f7b40f8e2504628bc0e

2024-12-27 23:15 UTC, flossybloom67 approved these changes

2024-12-27 23:15 UTC, flossybloom67 commented on README.md
>  #### Debian and variants
3f0288fcad8777955fb41f7b40f8e2504628bc0e